version: '{branch}-build{build}'
image: Ubuntu1804

skip_commits:
  files:
    - '**/*.md'

build_script:
  - sh: dotnet build -c Release

before_test:
  - sh: dotnet tool install --global coverlet.console 

test_script:
  - sh: dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*" ./TogglApi.Client.Tests/TogglApi.Client.Tests.csproj

after_test:
  - sh: dotnet pack ${APPVEYOR_BUILD_FOLDER}/TogglApi.Client -c Release --include-symbols --no-build -o artifacts/nuget
  - sh: wget 'https://codecov.io/bash' > codecov.sh
  - sh: chmod +x codecov.sh
  - sh: ./codecov.sh -f "coverage.opencover.xml"

artifacts:
  - path: '**/artifacts/nuget/*.nupkg'
    name: NuGet

deploy:
  - provider: NuGet
    api_key:
      secure: w+LEM1uajW6SNuodaIU2CGSnjaXPNNW9mXOw5zoXN8sk6xWrPE03NHueQbzoFkRp
    artifact: NuGet
    on:
      APPVEYOR_REPO_TAG: true