version: '{branch}-build{build}'
image: Ubuntu1804

skip_commits:
  files:
    - '**/*.md'

build_script:
  - sh: dotnet build -c Release

test_script:
  - sh: dotnet test -c Release --no-build

after_test:
  - sh: dotnet pack ${APPVEYOR_BUILD_FOLDER}/TogglApi.Client -c Release --include-symbols --no-build -o artifacts/nuget

artifacts:
  - path: '**/artifacts/nuget/*.nupkg'
    name: NuGet

deploy:
  - provider: NuGet
    api_key:
      secure: w+LEM1uajW6SNuodaIU2CGSnjaXPNNW9mXOw5zoXN8sk6xWrPE03NHueQbzoFkRp
    artifact: NuGet
    on:
      APPVEYOR_REPO_TAG: true