name: Nightly MyGet Package Deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: '5.x'
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.9
      - run: |
          echo "NuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
          echo "NuGetPreReleaseTagV2: ${{ steps.gitversion.outputs.CommitsSinceVersionSourcePadded }}"
      - name: build with .Net Core
        run: dotnet build --configuration Release
      - name: Pack with .Net Core
        run: dotnet pack --configuration Release --output nuget-packages -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}.${{ steps.gitversion.outputs.CommitsSinceVersionSourcePadded }}-nightly
      - uses: actions/upload-artifact@v2
        with:
          name: Nuget-packages-${{ steps.gitversion.outputs.nuGetVersionV2 }}.${{ steps.gitversion.outputs.CommitsSinceVersionSourcePadded }}-nightly
          path: nuget-packages
      - name: Push package to nuget
        run: dotnet nuget push 'nuget-packages/*.nupkg' --api-key ${{ secrets.MYGET_API_KEY }} --source https://www.myget.org/F/toggl-api-dotnet/api/v3/index.json